educloud:
  sql-log-level: DEBUG

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# mybatis-plus配置
mybatis-plus:
  # config-location:
  # classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mappers/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.xuegao.educloud.${spring.application.name}.client.entities,com.xuegao.educloud.${spring.application.name}.client.params
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    #cache-enabled: false
    #call-setters-on-nulls: true
    # 配置sql打印日志
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 是否控制台 print mybatis-plus 的 LOGO
    banner: false
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      select-strategy: NOT_NULL
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0


# feign 配置
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

# hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000




