educloud:
  config:
    ip-address: http://127.0.0.1
    eureka-port: 8761
    db-ip: 192.168.31.58


#eureka配置
eureka:
  client:
    # Eureka服务器的地址
    service-url:
      defaultZone: ${educloud.config.ip-address}:${educloud.config.eureka-port}/eureka/
  instance:
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    prefer-ip-address: true
    # 实例ID
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8002



spring:
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${educloud.config.db-ip}:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: xuegao
    password: xuegao
  application:
    name: user # 应用名称，将会显示在Eureka界面的应用名称列


